# Generated by Django 4.0.4 on 2022-04-24 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metsetgo_backend', '0004_alter_player_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPrivate', models.BooleanField()),
                ('datetime', models.DateTimeField()),
                ('skillMin', models.IntegerField()),
                ('skillMax', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=500)),
                ('isFull', models.BooleanField()),
                ('hostSkill', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMapEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metsetgo_backend.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metsetgo_backend.player')),
            ],
        ),
    ]
