# Generated by Django 4.0.4 on 2022-04-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metsetgo_backend', '0007_sport_playermapevent_playertype_eventmapvenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermapevent',
            name='playerType',
            field=models.CharField(default='Host', max_length=100),
        ),
    ]
