# Generated by Django 4.0.4 on 2022-04-25 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metsetgo_backend', '0008_alter_playermapevent_playertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metsetgo_backend.sport'),
        ),
    ]
