# Generated by Django 4.0.4 on 2022-04-25 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metsetgo_backend', '0009_event_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmapvenue',
            name='id',
        ),
        migrations.AlterField(
            model_name='eventmapvenue',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='metsetgo_backend.event'),
        ),
    ]
