# Generated by Django 4.0.4 on 2022-04-25 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metsetgo_backend', '0010_remove_eventmapvenue_id_alter_eventmapvenue_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventMapVenue',
        ),
    ]
