# Generated by Django 4.0.4 on 2022-04-25 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metsetgo_backend', '0011_delete_eventmapvenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMapVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eventVenue', to='metsetgo_backend.event')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metsetgo_backend.venue')),
            ],
        ),
    ]
