# Generated by Django 4.0.4 on 2022-04-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metsetgo_backend', '0014_event_sport_venue_playermapevent_eventmapvenue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='details',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='isFull',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='skillMax',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='skillMin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='playermapevent',
            name='playerType',
            field=models.CharField(choices=[('H', 'Host'), ('G', 'Guest'), ('I', 'Invited'), ('R', 'Requested')], default='R', max_length=100),
        ),
    ]
