# Generated by Django 4.0.4 on 2022-04-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metsetgo_backend', '0015_alter_event_details_alter_event_isfull_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isFinished',
            field=models.BooleanField(default=False),
        ),
    ]
