# Generated by Django 4.0.4 on 2022-04-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metsetgo_backend', '0022_event_venue_playermapevent_eventmapvenue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmapvenue',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Rejected'), ('A', 'Approved')], default='P', max_length=1),
        ),
    ]
