# Generated by Django 4.0.4 on 2022-04-26 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metsetgo_backend', '0024_remove_eventmapvenue_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPrivate', models.BooleanField(default=False)),
                ('startDateTime', models.DateTimeField()),
                ('endDateTime', models.DateTimeField()),
                ('skillMin', models.IntegerField(default=0)),
                ('skillMax', models.IntegerField(default=0)),
                ('type', models.CharField(blank=True, default='', max_length=100)),
                ('details', models.CharField(blank=True, default='', max_length=500)),
                ('isFull', models.BooleanField(default=False)),
                ('hostSkill', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='metsetgo_backend.player')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMapEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerType', models.CharField(choices=[('G', 'Guest'), ('I', 'Invited'), ('R', 'Requested')], default='R', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metsetgo_backend.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metsetgo_backend.player')),
            ],
        ),
        migrations.CreateModel(
            name='EventMapVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Rejected'), ('A', 'Approved')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eventVenue', to='metsetgo_backend.event')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metsetgo_backend.venue')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='players',
            field=models.ManyToManyField(related_name='players', through='metsetgo_backend.PlayerMapEvent', to='metsetgo_backend.player'),
        ),
        migrations.AddField(
            model_name='event',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metsetgo_backend.sport'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='metsetgo_backend.venue'),
        ),
    ]
