version: "3.9"

# secrets:
#   db_host:
#     file: ./secrets/db_host.txt
#   db_port:
#     file: ./secrets/db_port.txt
#   db_database:
#     file: ./secrets/db_database.txt
#   db_user:
#     file: ./secrets/db_user.txt
#   db_password:
#     file: ./secrets/db_password.txt
#   db_rootpassword:
#     file: ./secrets/db_rootpassword.txt


services:
  db:
    restart: always
    image: postgres:12.9
    container_name: metsetgo_database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=MetSetGoDB
    ports:
      - "5438:5432"
    networks:
      - db-net

  backend:
    restart: always
    container_name: metsetgo_backend
    command: bash -c "python manage.py makemigrations && 
                      python manage.py migrate && 
                      python manage.py runserver 0.0.0.0:8000"

#     env_file:
#       - ./metsetgo/.env
    build: 
      context: ./metsetgo
      dockerfile: Dockerfile
    command: gunicorn metsetgo.wsgi --bind 0.0.0.0:8000
    image: aravindv178/metsetgo:backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - db-net

  frontend:
    restart: always
    command: npm start
    container_name: metsetgo_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
     - ./react_build:/app/frontend/build
    image: aravindv178/metsetgo:frontend
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend
    networks:
      - db-net

  nginx: 
      image: nginx:latest
      ports:
        - 80:8080
      volumes:
        - ./nginx/nginx-setup.conf:/etx/nginx/conf.d/default.conf:ro
        - ./react_build:/var/www/react/

      depends_on:
        - backend
        - frontend


networks:
  # api:
  #   driver: bridge
  # db-network:
  #   driver: bridge
  db-net:
    driver: bridge

      
volumes:
  react-build: