const UserActionType = {
    GET_PROFILE: "GET_PROFILE",
    INVALID_TOKEN: "INVALID_TOKEN",
    GET_SPORTS: "GET_SPORTS",
    GET_VENUES: "GET_VENUES",
    CREATE_EVENT: "CREATE_EVENT",
    EDIT_EVENT: "EDIT_EVENT",
    GET_EVENT: "GET_EVENT",
    JOIN_EVENT: "JOIN_EVENT",
    GET_ALL_EVENTS: "GET_ALL_EVENTS",
}
export default UserActionType