---
- name: Deploy the application
  hosts: all
  become: true
  become_user: aravindv
  tasks:
    - name: Pull database image
      docker_image:
        name: aravindv178/metsetgo:db
        source: pull
    - name: Pull backend image
      docker_image:
        name: aravindv178/metsetgo:backend
        source: pull
    - name: Pull frontend image
      docker_image:
        name: aravindv178/metsetgo:frontend
        source: pull
    - name: Pull nginx image
      docker_image:
        name: aravindv178/metsetgo:nginx
        source: pull
    - name: Install pre-requisites and plugins
      ansible.builtin.shell:
        cmd: pip install docker-compose && ansible-galaxy collection install community.docker && ansible-galaxy collection install ansible.posix

    - name: Show pwd
      shell: pwd

    - name: Create directory if not exists
      file:
        path: ~/metsetgo
        state: directory
        mode: 0755

    - name: Copy docker compose file
      copy:
        src: /github/workspace/docker-compose.yml
        dest: ~/metsetgo/docker-compose.yml

    - name: Docker compose to spin up containers for metsetgo
      community.docker.docker_compose:
        project_src: ~/
        
