name: Push to DockerHub

on:
  push:
    branches:
    - deploy
  pull_request:
    branches:
    - deploy

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Pull base images
      run: docker-compose pull

    - name: Build images using docker compose
      run: docker-compose build
      
    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Tag docker images
      run: docker tag aravindv178/metsetgo:backend aravindv178/metsetgo:backend && docker tag aravindv178/metsetgo:frontend aravindv178/metsetgo:frontend && docker tag postgres:12.9 aravindv178/metsetgo:db
    
    - name: Push to DockerHub
      run: docker push aravindv178/metsetgo:backend && docker push aravindv178/metsetgo:frontend && docker push aravindv178/metsetgo:db
      
      
      
