name: Push to DockerHub

on:
  push:
    branches:
    - deploy
  pull_request:
    branches:
    - deploy

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Pull base images
      run: docker-compose pull

    - name: Build images using docker compose
      run: docker-compose build
      
    - name: Push to DockerHub
      uses: julioarruda/pushimagetoregistry@v1
      with:
        # Username Name with push permission
        acr-tokenname: ${{ secrets.DOCKERHUB_USERNAME }}
        # Token/PWD with push permission
        acr-token: ${{ secrets.DOCKERHUB_PASSWORD }}
        # Docker Account Name
        acr-account: ${{ secrets.DOCKERHUB_USERNAME }}
        # Docker Image Name
        acr-imagename: aravindv178/metsetgo:backend
      
      
      
      
